### PR TITLE
Fix entrypoint bug since vscode 1.64 (issue #24)

### PR DESCRIPTION
**Pull request by fortierq**
#24

### CODE REVIEW

**Review by qdm12 — APPROVED** [review]
Are you sure this is needed? I have this in a bunch of dev containers without issue.
What host OS are you running and what docker-compose version?

**Comment by temich-nosov** [comment]
I also had that problem with MacOS as a host system. This fix helps.

**Comment by qdm12** [comment]
I opened an issue at https://github.com/microsoft/vscode-remote-release/issues/6337

Feel free to 👍 it so it gets some attention 😉 Thanks again for the fix.

**Comment by qdm12** [comment]
For anyone ending up here, it should be fixed in the upcoming remote containers extension release.

See https://github.com/microsoft/vscode-remote-release/issues/6337#issuecomment-1048215351

**Pull request merged**
